version: '3'
services:
  influxdb:
    image: influxdb:1.5.2
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/mysql/data
    environment:
      INFLUXDB_DB: sandbox
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: sandbox
      INFLUXDB_USER_PASSWORD: sandbox
volumes:
  influxdb-data:
